name: build and deploy
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    my-job:
        name: my-job
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup bun.js
              uses: oven-sh/setup-bun@v1

            - name: install dependencies
              run: bun install && bun builds

            - name: SSH Upload
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_SSH_ID }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  source: "dist/*"
                  target: "${{secrets.TEMP_PATH}}/front"

            - name: SSH deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_SSH_ID }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      rm -r ${{secrets.DEPLOYPATH}}/front
                      mv ${{secrets.TEMP_PATH}}/front  ${{secrets.DEPLOYPATH}}/front
