name: build and deploy
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build_and_deplot:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: SSH deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_SSH_ID }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      source ~/.zshrc
                      cd ${{secrets.TEMP_PATH}}/front
                      git pull
                      bun install &&
                      bun vite build &&
                      rm -rf ${{secrets.DEPLOYPATH}}/front &&
                      mv ./dist  ${{secrets.DEPLOYPATH}}/front
